### ISSUE TITLE
Add stylua.toml file

### ISSUE THREAD

**Issue by ram02z** [ram02z/dotfiles#24]
```toml
column_width = 120
line_endings = "Unix"
indent_type = "Spaces"
indent_width = 2
quote_style = "AutoPreferDouble"
no_call_parentheses = false
```
